---
title: "Can LLMs Perform Data Analysis?"
subtitle: "My subtitle if needed"
author: Evelyn Hughes
thanks: "Code and data are available at: [https://github.com/EveHughes/Can-LLMs-Perform-Data-Analysis](https://github.com/EveHughes/Can-LLMs-Perform-Data-Analysis)."
date: today
date-format: long
abstract: "	LLMs have become widely known and popular for their ability to perform a large variety of tasks. Recently, there has been a growing interest in determining their ability to perform more technical tasks such as data analysis. (With the increase in LLM use for data analysis tasks, it becomes increasingly important to understand and quantify their abilities in this area.) Currently, there is a lack of insight into this area given the lack of an efficient “evaluation pipeline”. In this paper, we first create such an “evaluation pipeline”, and then use it to evaluate popular models on their ability to perform data analysis.We find _____ . As LLMs become increasingly involved in data analysis, it becomes important to understand their capabilities.Being able to efficiently quantify LLMs ability in these tasks improves both transparency and trust, both fundamental to science."
format: pdf
number-sections: true
bibliography: references.bib
---


# Introduction

Overview paragraph

Estimand paragraph

Results paragraph

Why it matters paragraph

Telegraphing paragraph: The remainder of this paper is structured as follows. @sec-data....


# Data {#sec-data}

## Overview

We use the statistical programming language R [@citeR].... Our data [@shelter].... Following @tellingstories, we consider...

Overview text

## Measurement
	
Some paragraphs about how we go from a phenomena in the world to an entry in the dataset.

## Outcome variables

Add graphs, tables and text. Use sub-sub-headings for each outcome variable or update the subheading to be singular.

## Predictor variables

Add graphs, tables and text.

Use sub-sub-headings for each outcome variable and feel free to combine a few into one if they go together naturally.


# Results

```{python}
#| label: fig-raw
#| fig-cap: Bills of penguins
#| echo: false

#set up
import polars as pl
import matplotlib.pyplot as plt
pl.Config.set_tbl_hide_column_data_types(True)  

#reading in
raw_data = pl.read_csv("../data/00-simulated_data/raw_grade.csv")

#creating table
raw_data
```

(@fig-raw) shows the scores of each model on the rubric, with categories aggregated.

```{python}
#| label: fig-analysis
#| fig-cap: Bills of penguins
#| echo: false

#set up
import polars as pl
import matplotlib.pyplot as plt
pl.Config.set_tbl_hide_column_data_types(True)  

#reading in
raw_data = pl.read_csv("../data/00-simulated_data/aggregated_scores.csv")

#creating table
raw_data
```

(@fig-analysis) shows the scores of each model aggregated across categories


# Discussion

## First discussion point {#sec-first-point}

If my paper were 10 pages, then should be be at least 2.5 pages. The discussion is a chance to show off what you know and what you learnt from all this. 

## Second discussion point

Please don't use these as sub-heading labels - change them to be what your point actually is.

## Third discussion point

## Weaknesses and next steps

Weaknesses and next steps should also be included.

\newpage

\appendix

# Appendix {-}

